import type { Locale } from '@/preferences/model';

const copy = {
  en: { title: 'Trade plans', new: 'New trade plan', edit: 'Trade plan', hint: 'Record the conditions for a decision before acting.', symbol: 'Symbol', status: 'Status', draft: 'Draft', active: 'Active', closed: 'Closed', cancelled: 'Cancelled', setupType: 'Setup', entryPrice: 'Entry price', entryZoneLow: 'Entry zone low', entryZoneHigh: 'Entry zone high', stopLoss: 'Stop loss', targetPrice: 'Target price', maxPositionSize: 'Maximum position size', invalidationCondition: 'Invalidation condition', notes: 'Notes', diaryId: 'Linked diary', none: 'No linked diary', save: 'Save trade plan', remove: 'Delete trade plan', confirm: 'Delete this trade plan?', discard: 'Discard unsaved changes?', back: 'All trade plans', levels: 'Price and position limits', context: 'Decision context', precision: 'Prices accept up to 6 decimal places; position size accepts 2. Values are never rounded.', empty: 'No trade plans match these filters.', filter: 'Apply filters', all: 'All statuses', previous: 'Previous', next: 'Next', diaries: 'Load more diaries', saved: 'Trade plan saved.', read: 'Read linked diary', sort: 'Sort', updated: 'Recently updated', created: 'Recently created', symbols: 'Symbol A–Z', loading: 'Loading trade plans…', failure: 'Could not load trade plans. Retry.', rejected: 'The server rejected this plan. Check the fields and try again.', uncertain: 'Save outcome is uncertain. Check the plan list or detail before submitting again.', network: 'An online connection is required to save this plan.', validation: 'Check the highlighted fields.', zone: 'The high entry price must be at least the low entry price.', search: 'Filter by symbol', select: 'Choose', unlink: 'Unlink diary', chooseDiary: 'Choose a diary', diaryFailure: 'Could not load diaries. Retry.', noDiary: 'No diaries found.', deleteUncertain: 'Delete outcome is uncertain. Check the plan list before trying again.', deleted: 'Trade plan deleted.', noPlan: 'This trade plan is unavailable.', page: 'Page', of: 'of', drafts: 'Unsaved plan edits are kept on this device.', draftFailure: 'Could not protect the plan draft on this device.', restore: 'Restore saved draft', savedDraft: 'Saved local draft', continue: 'Continue editing', retry: 'Retry', cancel: 'Cancel', close: 'Close', clear: 'Clear filters' },
  'zh-TW': { title: '交易計劃', new: '新增交易計劃', edit: '交易計劃', hint: '行動之前，記錄決策所需的條件。', symbol: '股票代號', status: '狀態', draft: '草稿', active: '進行中', closed: '已結束', cancelled: '已取消', setupType: '策略形態', entryPrice: '進場價格', entryZoneLow: '進場區間下限', entryZoneHigh: '進場區間上限', stopLoss: '停損價格', targetPrice: '目標價格', maxPositionSize: '部位上限', invalidationCondition: '失效條件', notes: '備註', diaryId: '關聯日記', none: '不關聯日記', save: '儲存交易計劃', remove: '刪除交易計劃', confirm: '刪除這個交易計劃？', discard: '捨棄未儲存的修改？', back: '全部交易計劃', levels: '價格與部位限制', context: '決策背景', precision: '價格最多六位小數；部位上限最多兩位。數值不會被四捨五入。', empty: '沒有符合篩選條件的交易計劃。', filter: '套用篩選', all: '全部狀態', previous: '上一頁', next: '下一頁', diaries: '載入更多日記', saved: '交易計劃已儲存。', read: '閱讀關聯日記', sort: '排序', updated: '最近更新', created: '最近建立', symbols: '股票代號 A–Z', loading: '正在載入交易計劃…', failure: '無法載入交易計劃，請重試。', rejected: '伺服器拒絕了此計劃。請檢查欄位後重試。', uncertain: '無法確認儲存結果。再次提交前請先檢查計劃清單或詳情。', network: '儲存計劃需要網絡連線。', validation: '請檢查標示的欄位。', zone: '進場區間上限須大於或等於下限。', search: '按股票代號篩選', select: '選擇', unlink: '取消關聯日記', chooseDiary: '選擇日記', diaryFailure: '無法載入日記，請重試。', noDiary: '找不到日記。', deleteUncertain: '無法確認刪除結果。再次嘗試前請先檢查計劃清單。', deleted: '交易計劃已刪除。', noPlan: '無法查看此交易計劃。', page: '第', of: '／', drafts: '未儲存的計劃修改會保留在此裝置。', draftFailure: '無法在此裝置保護計劃草稿。', restore: '還原已儲存草稿', savedDraft: '已儲存本機草稿', continue: '繼續編輯', retry: '重試', cancel: '取消', close: '關閉', clear: '清除篩選' },
  'zh-CN': { title: '交易计划', new: '新增交易计划', edit: '交易计划', hint: '行动之前，记录决策所需的条件。', symbol: '股票代码', status: '状态', draft: '草稿', active: '进行中', closed: '已结束', cancelled: '已取消', setupType: '策略形态', entryPrice: '进场价格', entryZoneLow: '进场区间下限', entryZoneHigh: '进场区间上限', stopLoss: '止损价格', targetPrice: '目标价格', maxPositionSize: '仓位上限', invalidationCondition: '失效条件', notes: '备注', diaryId: '关联日记', none: '不关联日记', save: '保存交易计划', remove: '删除交易计划', confirm: '删除这个交易计划？', discard: '放弃未保存的修改？', back: '全部交易计划', levels: '价格与仓位限制', context: '决策背景', precision: '价格最多六位小数；仓位上限最多两位。数值不会被四舍五入。', empty: '没有符合筛选条件的交易计划。', filter: '应用筛选', all: '全部状态', previous: '上一页', next: '下一页', diaries: '加载更多日记', saved: '交易计划已保存。', read: '阅读关联日记', sort: '排序', updated: '最近更新', created: '最近创建', symbols: '股票代码 A–Z', loading: '正在加载交易计划…', failure: '无法加载交易计划，请重试。', rejected: '服务器拒绝了此计划。请检查字段后重试。', uncertain: '无法确认保存结果。再次提交前请先检查计划列表或详情。', network: '保存计划需要网络连接。', validation: '请检查标出的字段。', zone: '进场区间上限须大于或等于下限。', search: '按股票代码筛选', select: '选择', unlink: '取消关联日记', chooseDiary: '选择日记', diaryFailure: '无法加载日记，请重试。', noDiary: '找不到日记。', deleteUncertain: '无法确认删除结果。再次尝试前请先检查计划列表。', deleted: '交易计划已删除。', noPlan: '无法查看此交易计划。', page: '第', of: '／', drafts: '未保存的计划修改会保留在此设备。', draftFailure: '无法在此设备保护计划草稿。', restore: '恢复已保存草稿', savedDraft: '已保存本机草稿', continue: '继续编辑', retry: '重试', cancel: '取消', close: '关闭', clear: '清除筛选' },
} as const;
export function planCopy(locale: Locale) { return copy[locale] ?? copy.en; }
export const leaveCopy = {
  en: { title: 'Unsaved plan changes', message: 'Keep the encrypted local draft before leaving?', uncertain: 'The exact attempted save is retained. Leaving does not cancel a request that may still complete.', keep: 'Keep draft and leave', discard: 'Discard draft and leave', stay: 'Stay here' },
  'zh-TW': { title: '尚未儲存的計劃修改', message: '離開前保留加密本機草稿？', uncertain: '已保留原本送出的內容。離開不會取消可能仍在完成的請求。', keep: '保留草稿並離開', discard: '捨棄草稿並離開', stay: '留在這裡' },
  'zh-CN': { title: '尚未保存的计划修改', message: '离开前保留加密本机草稿？', uncertain: '已保留原本提交的内容。离开不会取消可能仍在完成的请求。', keep: '保留草稿并离开', discard: '放弃草稿并离开', stay: '留在这里' },
} as const;
